version: 2
jobs:
  build:
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get -y install locales make
            apt-get -y install util-linux bsdmainutils gawk curl rlwrap emacs
      - run:
          name: Sanity Check
          command: |
            make test
